    // Lokalny słownik definicji – klucze zapisujemy w lowercase
    const polishDefinitions = {
        // Pierwsze dania
        "zupa kalafiorowa zabielana": "Delikatna zupa na bazie kalafiora, zabielana śmietaną, o łagodnym smaku.",
        "krupnik z kaszy wiejskiej jęczmiennej z ziemniakami": "Sycący krupnik na bazie kaszy wiejskiej jęczmiennej, z dodatkiem ziemniaków, aromatycznie przyprawiony.",
        "zupa pomidorowa z makaronem": "Klasyczna zupa pomidorowa z dodatkiem makaronu, lekko przyprawiona bazylią i oregano.",
        "zupa szczawiowa z jajkiem": "Orzeźwiająca zupa szczawiowa, podawana z ugotowanym jajkiem, idealna na wiosnę.",
        "zupa z zielonej fasolki szparagowej": "Lekka i kremowa zupa z młodej zielonej fasolki szparagowej, o subtelnym smaku.",
        "rosół z makaronem": "Tradycyjny, klarowny rosół drobiowy podawany z makaronem, z nutą przypraw.",
        "zupa buraczkowa zabielana": "Buraczkowa zupa o słodko-kwaskowatym smaku, zabielana śmietaną.",
        "zupa tajska z kurczakiem": "Egzotyczna zupa tajska z dodatkiem kurczaka, aromatyzowana mlekiem kokosowym i przyprawami curry.",
        "zupa owocowa z zacierką": "Lekka, owocowa zupa z dodatkiem zacierki, idealna na letnie dni.",
        "zupa kapuśniak z młodej kapusty": "Tradycyjny kapuśniak przygotowany z młodej kapusty, o wyrazistym, kwaskowatym smaku.",
        "zupa jarzynowa zabielana": "Zdrowa i sycąca zupa jarzynowa, zabielana śmietaną, pełna sezonowych warzyw.",
        "zupa neapolitańska z makaronem": "Zupa inspirowana kuchnią włoską, z dodatkiem makaronu i pomidorów, o intensywnym smaku.",
        "zupa minestrone": "Gęsta włoska zupa warzywna z dodatkiem fasoli i makaronu, bogata w składniki odżywcze.",
        "zupa krem warzywny": "Kremowa zupa z mieszanki sezonowych warzyw, idealna dla miłośników delikatnych smaków.",
        "zupa brokułowa zabielana": "Zupa z brokułów, delikatnie zabielana, z nutą czosnku i parmezanu.",
        "zupa rosół z zacierką": "Alternatywna wersja tradycyjnego rosołu, podawana z domową zacierką.",
        "zupa krupnik z ziemniakami": "Krupnik przygotowany z kaszy, z dodatkiem ziemniaków, lekko przyprawiony i sycący.",
  
        // Drugie dania
        "kotlet pożarski, ziemniaki puree, surówka": "Soczysty kotlet pożarski podawany z kremowym puree ziemniaczanym i świeżą surówką.",
        "racuchy drożdżowe z jabłkami i cukrem pudrem": "Puszyste racuchy drożdżowe z dodatkiem słodkich jabłek, posypane cukrem pudrem.",
        "gulasz wieprzowy z szynki, kasza, surówka": "Aromatyczny gulasz wieprzowy z szynki, serwowany z kaszą i surówką.",
        "kotlet z kalafiora z ziemniakami, surówka": "Zdrowa alternatywa kotlet z kalafiora, podawany z ziemniakami i surówką.",
        "kurczak w sosie potrawkowym z warzywami, kasza bulgur, surówka": "Delikatny kurczak duszony w aromatycznym sosie z warzywami, serwowany z kaszą bulgur i surówką.",
        "schab po parysku, ziemniaki, surówka": "Schab przygotowany według paryskiej receptury, podawany z ziemniakami i świeżą surówką.",
        "kotlet mielony, ziemniaki, surówka": "Tradycyjny kotlet mielony, podawany z ziemniakami oraz surówką.",
        "pierogi z owocami i twarogiem": "Słodkie pierogi nadziewane mieszanką owoców i delikatnego twarogu, idealne na deser.",
        "kotlet ziemniaczany z sosem pieczarkowym, surówka": "Kotlet ziemniaczany serwowany z aromatycznym sosem pieczarkowym oraz surówką.",
        "makaron z sosem bolognese": "Klasyczny makaron z gęstym sosem bolognese, przygotowanym na bazie mięsa i pomidorów.",
        "pieczeń z szynki , ziemniaki, surówka": "Soczysta pieczeń z szynki, podawana z ziemniakami i surówką.",
        "gulasz drobiowy z pomidorami, kasza bulgur, surówka": "Lekkie danie z drobiu duszonego z pomidorami, podawane z kaszą bulgur i surówką.",
        "placki z jabłkiem i marchewką z cukrem pudrem": "Chrupiące placki z dodatkiem jabłek i marchewki, posypane cukrem pudrem.",
        "pulpety w sosie koperkowym, ziemniaki, surówka": "Małe pulpety mięsne w delikatnym sosie koperkowym, serwowane z ziemniakami i surówką.",
        "paluszki rybne, ziemniak puree, surówka": "Chrupiące paluszki rybne, podawane z ziemniakowym puree i świeżą surówką.",
        "pierogi ruskie": "Tradycyjne pierogi z farszem z ziemniaków i twarogu, lekko podsmażane na złoty kolor.",
        "tortilla z kurczakiem": "Meksykańska tortilla wypełniona soczystym kurczakiem, warzywami i aromatycznymi przyprawami.",
        "gołąbki odwrotnie w sosie pomidorowym, ziemniaki, surówka z buraczków": "Innowacyjna wersja gołąbków, podawana w sosie pomidorowym z ziemniakami i surówką z buraczków.",
        // Nowe definicje
        "stripsy z kurczaka, ziemniaki łódeczki, surówka": "Chrupiące paski panierowanego kurczaka, podawane z pieczonymi ziemniakami w kształcie łódeczek i świeżą surówką.",
        "zupa ogórkowa": "Kremowa lub klarowna zupa na bazie kiszonych ogórków, często z dodatkiem ziemniaków i śmietany.",
        "makaron z pomidorami i serem mozzarella": "Delikatny makaron z sosem pomidorowym, podany z kawałkami mozzarelli, która delikatnie się rozpuszcza.",
        "zupa krem z białych warzyw": "Gęsty, aksamitny krem z białych warzyw (np. kalafior, seler, pietruszka), często zabielany.",
        "schab w jajku, ziemniaki puree, surówka": "Panierowany kotlet schabowy w jajku, podawany z gładkim puree ziemniaczanym i surówką.",
        "zupa neapolitańska-serowa": "Aromatyczna zupa pomidorowa z dodatkiem sera, przyprawiona bazylią i oregano.",
        "pampuchy z sosem owocowym": "Miękkie kluski na parze (pampuchy), podawane z gęstym sosem z owoców sezonowych.",
        "kurczak pieczony, ziemniaki, surówka": "Soczyste mięso kurczaka pieczone w przyprawach, serwowane z ziemniakami i surówką.",
        "pierogi z mięsem okraszane cebulką": "Pierogi z nadzieniem mięsnym, podawane z podsmażoną cebulką.",
        "naleśniki z twarogiem": "Cienkie naleśniki wypełnione słodkim serem twarogowym, często podane z cukrem pudrem lub śmietaną.",
        "kotlet pożarski z kurczaka, ziemniaki, surówka": "Soczysty mielony kotlet z kurczaka, podawany z ziemniakami i surówką.",
        "zupa rosół": "Wywar mięsno-warzywny, klarowny i aromatyczny, podawany często z makaronem lub kluskami.",
        "gulasz drobiowy, kasza, surówka": "Drobiowy gulasz duszony w sosie własnym, podany z kaszą i świeżą surówką.",
        "pierogi leniwe z jogurtem i cynamonem": "Małe pierogi z serem i ziemniakami, polane jogurtem i posypane cynamonem.",
        "ryba w panierce, ziemniaki puree, surówka": "Filet rybny w chrupiącej panierce, serwowany z puree ziemniaczanym i surówką.",
        "klopsiki w sosie koperkowym, ziemniaki, surówka": "Mięsne klopsiki w delikatnym sosie koperkowym, podawane z ziemniakami i surówką.",
        "burger drobiowy": "Soczysty burger z mielonego mięsa drobiowego, często podany w bułce z dodatkami.",
        "zupa pieczarkowa": "Kremowa zupa na bazie świeżych pieczarek, często z dodatkiem śmietany i czosnku.",
        "zupa z fasolki szparagowej z ziemniakami": "Lekka zupa na bazie zielonej fasolki szparagowej i ziemniaków, często doprawiona czosnkiem.",
        "stripsy z kurczaka, ziemniak opiekany, surówka": "Chrupiące paski kurczaka, podawane z opiekanymi ziemniakami i surówką."  ,
        // ...wcześniejsze definicje
  "racuchy drożdżowe z jabłkiem": "Puszyste placuszki drożdżowe z kawałkami jabłek, delikatnie słodzone i podsypane cukrem pudrem.",
  "kotlet z kalafiora, ziemniaki puree, surówka": "Kotlety z gotowanego i siekanego kalafiora, podawane z aksamitnym puree ziemniaczanym i świeżą surówką.",
  "zupa serowa z makaronem": "Aromatyczna zupa na bazie roztopionego sera, z dodatkiem drobnego makaronu, kremowa i sycąca.",
  "zupa buraczkowa": "Kwaśna zupa na bazie gotowanych buraków, często podawana z ziemniakami i śmietaną lub jogurtem naturalnym.",
  "klopsiki w sosie koperkowym, ziemniaki, surówka": "Mięsne klopsiki duszone w delikatnym sosie koperkowym, serwowane z ziemniakami i surówką.",
  "gulasz drobiowy, kasza, surówka": "Drobiowy gulasz w aromatycznym sosie własnym, podany z kaszą (np. jęczmienną) i świeżą surówką.",
  "kapuśniak z białej młodej kapusty": "Pogęszczona zupa na bazie młodej białej kapusty, z dodatkiem wędzonego mięsa lub żeber, lekko kwaskowa.",
  "zupa buraczkowa z jajkiem": "Buraczkowa zupa z dodatkiem ugotowanego jajka na twardo, kremowa i lekko słodkawa.",
  "zupa jarzynowa z ziemniakami": "Klasyczna zupa warzywna z marchewką, selerem, pietruszką i ziemniakami, podawana często z dodatkiem śmietany.",
  "gulasz wieprzowy z warzywami, ziemniaki, surówka": "Kawałki wieprzowiny duszone z warzywami, serwowane z ziemniakami i surówką.",
  "zupa kalafiorowa z ziemniakami": "Delikatna zupa z różyczek kalafiora i ziemniaków, często zabielana śmietaną.",
  "zupa krupnik z kaszy jęczmiennej": "Treściwy krupnik na wywarze mięsnym z dodatkiem kaszy jęczmiennej i warzyw.",
  // ...następne definicje
      };