<?php
// Słownik opisów dań z wcześniejszych jadłospisów szkoły (dawniej definitions.js).
// Używany, gdy AI nie jest skonfigurowane albo nie odpowiada; nazwy porównujemy
// bez wielkich liter, polskich znaków i interpunkcji. Gdy AI zacznie działać,
// opisy ze słownika w bazie zostaną zastąpione opisami AI.
return [
    // Zupy
    'zupa kalafiorowa zabielana' => 'Zupa z kalafiora, zwykle z ziemniakami i marchewką, zabielana śmietaną.',
    'krupnik z kaszy wiejskiej jęczmiennej z ziemniakami' => 'Zupa z kaszą jęczmienną, ziemniakami i warzywami, gotowana na wywarze.',
    'zupa pomidorowa z makaronem' => 'Zupa z pomidorów lub przecieru pomidorowego na wywarze, podawana z makaronem.',
    'zupa szczawiowa z jajkiem' => 'Kwaskowa zupa ze szczawiu, zwykle zabielana, podawana z jajkiem ugotowanym na twardo.',
    'zupa z zielonej fasolki szparagowej' => 'Zupa z zielonej fasolki szparagowej, zwykle z ziemniakami i koperkiem.',
    'rosół z makaronem' => 'Klarowny wywar z mięsa i warzyw, podawany z makaronem.',
    'zupa buraczkowa zabielana' => 'Zupa z buraków o słodko kwaskowym smaku, zabielana śmietaną.',
    'zupa tajska z kurczakiem' => 'Zupa w stylu tajskim z kurczakiem, warzywami i mlekiem kokosowym, doprawiona curry.',
    'zupa owocowa z zacierką' => 'Słodka zupa z owoców, podawana z zacierką, czyli drobnymi kluseczkami z ciasta.',
    'zupa kapuśniak z młodej kapusty' => 'Kapuśniak, czyli zupa z poszatkowanej młodej kapusty z ziemniakami i warzywami.',
    'zupa jarzynowa zabielana' => 'Zupa z mieszanki warzyw, zwykle z ziemniakami, zabielana śmietaną.',
    'zupa neapolitańska z makaronem' => 'Zupa pomidorowa w stylu włoskim, zwykle z serem i ziołami, podawana z makaronem.',
    'zupa minestrone' => 'Gęsta włoska zupa warzywna, zwykle z fasolą, pomidorami i makaronem.',
    'zupa krem warzywny' => 'Zmiksowana na gładko zupa z mieszanki warzyw.',
    'zupa brokułowa zabielana' => 'Zupa z brokułów, zwykle z ziemniakami, zabielana śmietaną.',
    'zupa rosół z zacierką' => 'Klarowny wywar z mięsa i warzyw, podawany z zacierką, czyli drobnymi kluseczkami z ciasta.',
    'zupa krupnik z ziemniakami' => 'Zupa z kaszą, zwykle jęczmienną, z ziemniakami i warzywami.',
    'zupa ogórkowa' => 'Zupa z kiszonych ogórków, zwykle z ziemniakami, często zabielana.',
    'zupa krem z białych warzyw' => 'Zmiksowana na gładko zupa z białych warzyw, takich jak kalafior, seler i pietruszka.',
    'zupa neapolitańska-serowa' => 'Zupa pomidorowa z dodatkiem sera, doprawiona ziołami.',
    'zupa rosół' => 'Klarowny wywar z mięsa i warzyw, zwykle podawany z makaronem albo kluskami.',
    'zupa pieczarkowa' => 'Zupa z pieczarek, zwykle z ziemniakami lub makaronem, zabielana śmietaną.',
    'zupa z fasolki szparagowej z ziemniakami' => 'Zupa z zielonej fasolki szparagowej i ziemniaków.',
    'zupa serowa z makaronem' => 'Zupa z roztopionym serem, kremowa, podawana z drobnym makaronem.',
    'zupa buraczkowa' => 'Zupa z gotowanych buraków o słodko kwaskowym smaku, często z ziemniakami.',
    'kapuśniak z białej młodej kapusty' => 'Zupa z młodej białej kapusty z ziemniakami i warzywami, lekko kwaskowa.',
    'zupa buraczkowa z jajkiem' => 'Zupa z buraków podawana z jajkiem ugotowanym na twardo.',
    'zupa jarzynowa z ziemniakami' => 'Zupa z marchewki, selera, pietruszki i innych warzyw, z ziemniakami.',
    'zupa kalafiorowa z ziemniakami' => 'Zupa z różyczek kalafiora i ziemniaków, często zabielana śmietaną.',
    'zupa krupnik z kaszy jęczmiennej' => 'Zupa na wywarze z kaszą jęczmienną i warzywami.',

    // Drugie dania
    'kotlet pożarski, ziemniaki puree, surówka' => 'Panierowany kotlet z mielonego mięsa drobiowego, podawany z puree ziemniaczanym i surówką.',
    'racuchy drożdżowe z jabłkami i cukrem pudrem' => 'Smażone placuszki z ciasta drożdżowego z kawałkami jabłek, posypane cukrem pudrem.',
    'gulasz wieprzowy z szynki, kasza, surówka' => 'Kawałki wieprzowej szynki duszone w sosie, podawane z kaszą i surówką.',
    'kurczak w sosie potrawkowym z warzywami, kasza bulgur, surówka' => 'Kurczak duszony z warzywami w jasnym sosie, podawany z kaszą bulgur i surówką.',
    'schab po parysku, ziemniaki, surówka' => 'Plastry schabu obtoczone w mące i jajku, smażone, podawane z ziemniakami i surówką.',
    'kotlet mielony, ziemniaki, surówka' => 'Smażony kotlet z mięsa mielonego, podawany z ziemniakami i surówką.',
    'pierogi z owocami i twarogiem' => 'Słodkie pierogi z nadzieniem z owoców i twarogu.',
    'kotlet ziemniaczany z sosem pieczarkowym, surówka' => 'Kotlet z ziemniaków podawany z sosem z pieczarek i surówką.',
    'makaron z sosem bolognese' => 'Makaron z gęstym sosem z mięsa mielonego i pomidorów.',
    'pieczeń z szynki, ziemniaki, surówka' => 'Pieczona w całości szynka wieprzowa krojona w plastry, podawana z ziemniakami i surówką.',
    'placki z jabłkiem i marchewką z cukrem pudrem' => 'Smażone placuszki z dodatkiem startego jabłka i marchewki, posypane cukrem pudrem.',
    'pulpety w sosie koperkowym, ziemniaki, surówka' => 'Gotowane kulki z mięsa mielonego w sosie koperkowym, podawane z ziemniakami i surówką.',
    'paluszki rybne, ziemniak puree, surówka' => 'Panierowane paluszki z ryby, podawane z puree ziemniaczanym i surówką.',
    'pierogi ruskie' => 'Pierogi z nadzieniem z ziemniaków i twarogu, zwykle z cebulką.',
    'tortilla z kurczakiem' => 'Pszenny placek zawinięty z kurczakiem, warzywami i sosem.',
    'gołąbki odwrotnie w sosie pomidorowym, ziemniaki, surówka z buraczków' => 'Gołąbki bez zawijania: mięso mielone z ryżem i poszatkowaną kapustą, duszone w sosie pomidorowym, z ziemniakami i surówką z buraczków.',
    'stripsy z kurczaka, ziemniaki łódeczki, surówka' => 'Paski kurczaka w chrupiącej panierce, podawane z pieczonymi ziemniakami w kształcie łódeczek i surówką.',
    'makaron z pomidorami i serem mozzarella' => 'Makaron z sosem pomidorowym i kawałkami sera mozzarella.',
    'schab w jajku, ziemniaki puree, surówka' => 'Plastry schabu smażone w jajku, podawane z puree ziemniaczanym i surówką.',
    'pampuchy z sosem owocowym' => 'Drożdżowe kluski gotowane na parze, podawane z sosem owocowym.',
    'kurczak pieczony, ziemniaki, surówka' => 'Kurczak pieczony w przyprawach, podawany z ziemniakami i surówką.',
    'pierogi z mięsem okraszane cebulką' => 'Pierogi z nadzieniem mięsnym, polane podsmażoną cebulką.',
    'naleśniki z twarogiem' => 'Cienkie naleśniki zwinięte z nadzieniem z twarogu, zwykle na słodko.',
    'kotlet pożarski z kurczaka, ziemniaki, surówka' => 'Panierowany kotlet z mielonego mięsa z kurczaka, podawany z ziemniakami i surówką.',
    'gulasz drobiowy, kasza, surówka' => 'Kawałki drobiu duszone w sosie, podawane z kaszą i surówką.',
    'pierogi leniwe z jogurtem i cynamonem' => 'Kluski z twarogu, mąki i jajek, podawane z jogurtem i cynamonem.',
    'ryba w panierce, ziemniaki puree, surówka' => 'Filet rybny w panierce, podawany z puree ziemniaczanym i surówką.',
    'klopsiki w sosie koperkowym, ziemniaki, surówka' => 'Kulki z mięsa mielonego w sosie koperkowym, podawane z ziemniakami i surówką.',
    'burger drobiowy' => 'Kotlet z mielonego mięsa drobiowego w bułce z warzywami i sosem.',
    'stripsy z kurczaka, ziemniak opiekany, surówka' => 'Paski kurczaka w chrupiącej panierce, podawane z opiekanymi ziemniakami i surówką.',
    'kotlet z kalafiora, ziemniaki puree, surówka' => 'Kotlety z gotowanego, rozdrobnionego kalafiora, podawane z puree ziemniaczanym i surówką.',
    'gulasz wieprzowy z warzywami, ziemniaki, surówka' => 'Kawałki wieprzowiny duszone z warzywami, podawane z ziemniakami i surówką.',
    'klops w sosie, ziemniaki, surówka' => 'Pieczony klops z mięsa mielonego krojony w plastry, podawany w sosie z ziemniakami i surówką.',
];
